### ISSUE TITLE
"Check your inputs. Multiple input was set or missing input"

### ISSUE THREAD

**Issue by undercovervictory** [Akegarasu/sd-webui-model-converter#20]
Hi, I got this error today. I seemed to be converting models fine yesterday but not now. Have tried deleting and reinstalling extension, still the same thing. Using the latest version. Is there something wrong on my end? I'm just converting to fp16 + safetensors and deleting vae as normal, tried other settings but still the same thing...

edit: closed and tried again several times, here's the log message:

Traceback (most recent call last):
  File "W:\!!SDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "W:\!!SDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "W:\!!SDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "W:\!!SDiffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "W:\!!SDiffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "W:\!!SDiffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "W:\!!SDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "W:\!!SDiffusion\stable-diffusion-webui\extensions\sd-webui-model-converter\scripts\convert.py", line 125, in convert_warp
    return do_convert(sd_models.checkpoints_list[model_name])
TypeError: do_convert() missing 11 required positional arguments: 'checkpoint_formats', 'precision', 'conv_type', 'custom_name', 'unet_conv', 'text_encoder_conv', 'vae_conv', 'others_conv', 'fix_clip', 'force_position_id', and 'delete_known_junk_data'

**Comment by Akegarasu** [comment]
i will fix it soon

**Comment by Neytiri7** [comment]
I can't go back to the previous version, so I want you to revise it quickly.
